# Generated by Django 5.1.5 on 2026-02-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_special_offer_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='flight_departure_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
