from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import FlightViewSet, BookingViewSet, FoodOrderViewSet, AIChatView

# Routers are ONLY for ViewSets (classes that have multiple actions like list, create, etc.)
router = DefaultRouter()
router.register(r'flights', FlightViewSet)
router.register(r'bookings', BookingViewSet)
router.register(r'food-orders', FoodOrderViewSet)

urlpatterns = [
    # 1. Include all routes generated by the router (flights, bookings, food-orders)
    path('', include(router.urls)),
    
    # 2. Add the AI Chat route manually (because it is a single APIView endpoints)
     path('chat/', AIChatView.as_view(), name='ai_chat'),
]