# Generated by Django 5.1.5 on 2026-02-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_booking_flight_departure_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='BOOKED', max_length=20),
        ),
    ]
