# Generated by Django 5.1.5 on 2026-05-26 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_booking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('HONEYMOON', 'Honeymoon Special'), ('HOLIDAY', 'Holiday Escape'), ('WEEKEND', 'Weekend Trip'), ('FAMILY', 'Family & Kids'), ('GROUP', 'Group Tours')], max_length=50)),
                ('description', models.TextField()),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
                ('flight_inclusion', models.CharField(max_length=255)),
                ('hotel_inclusion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PackageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=255)),
                ('passenger_email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('local_transaction_id', models.CharField(blank=True, max_length=100)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.travelpackage')),
            ],
        ),
    ]
